### ISSUE TITLE
Add to Conan-center

### ISSUE THREAD

**Issue by kinokritik** [morganstanley/modern-cpp-kafka#105]
First of all thank you guys for the wrapper for modern C++!
Any chance you plan to add it to Conan center?

**Comment by kenneth-jia** [comment]
Hi, @kinokritik 
That sounds a good idea! While it depends on how much effort it would take -- I'm not sure about that, maybe I should take some time to learn Conan, 😅
What I can tell is, it would support Bazel in near future, then let's see how to move to Conan...

**Comment by kenneth-jia** [comment]
A PR would be submitted to https://github.com/conan-io/conan-center-index
Some references,
* https://docs.conan.io/en/latest/getting_started.html
* https://docs.conan.io/en/latest/howtos/header_only.html
* https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md
