### ISSUE TITLE
Debug Assertion Failed: vector subscript out of range when _maxPollRecords reaches the value of 500 

### ISSUE THREAD

**Issue by jquare** [morganstanley/modern-cpp-kafka#108]
Subscript out of range when _maxPollRecords reaches the value of 500 

Changing the default value using "max.poll.records" property fixes the issue if you don't reach the limit again.

// Wrap messages with ConsumerRecord
    output.clear();
    output.reserve(msgReceived);
=here===>    std::for_each(&msgPtrArray[0], &msgPtrArray[msgReceived], [&output](rd_kafka_message_t* rkMsg) { output.emplace_back(rkMsg); });

**Comment by kenneth-jia** [comment]
Did you get the error on a windows platform?
While I believe the problem has been fixed, https://github.com/morganstanley/modern-cpp-kafka/pull/100/files

**Comment by jquare** [comment]
On Windows. Yes, it seems to be fixed... I have to update my local copy, thanks!

**Comment by jquare** [comment]
On Windows. I have pending the update, but that seems not to solve the issue. The above change substitutes access operator [] with iterators, but nothing prevents that when the limit is reached a "array iterator + offset out of range" occurs .

**Comment by kenneth-jia** [comment]
> The above change substitutes access operator [] with iterators, but nothing prevents that when the limit is reached a "array iterator + offset out of range" occurs .

Oh, sorry, I'm not a fun of Microsoft and had not tried with a local windows dev env. 😅 Could you please share the error message you met? and the build environment? (Visual C++?)
Actually, the `array iterator + offset` would not be `out of range` (neither the previous implementation), we were just trying to get rid of the "false alarm".

**Comment by jquare** [comment]
Microsoft is not so bad, nowadays is in love with Linux ;-) 

Microsoft Visual Studio Community 2019 - Version 16.8.3

![image](https://user-images.githubusercontent.com/94577849/142842136-bb5f3014-b39f-4c08-9407-df4914423c18.png)
![image](https://user-images.githubusercontent.com/94577849/142842249-4c1cc4fb-1a09-485a-83ee-152d88b81732.png)

I have not had time to examine this issue in depth, and I'm sure I'm absolutely wrong, but it seems that a boundary condition needs to be managed in some way...

Thanks

**Comment by kenneth-jia** [comment]
Thank you for the detailed info, @jquare!
Could you please try with the fix from https://github.com/morganstanley/modern-cpp-kafka/pull/100?  (i.e. use `msgPtrArray.begin() + msgReceived`, instead of `&msgPtrArray[msgReceived]`) I guess it can't say "vector subscript out of range" this time? 🤔

**Comment by jquare** [comment]
It works perfectly. ``msgReceived`` never exceeds the limit set by ``_maxPollRecords`` and `msgPtrArray.begin() + msgReceived`  turns out to be a safe operation. The issue seems to have been solved by people smarter than me. Thank you very much, especially for creating a so elegant library that it abstracts you from ``librdkafka``
