### ISSUE TITLE
how to use SASL credentials?

### ISSUE THREAD

**Issue by rahulsharma11** [morganstanley/modern-cpp-kafka#116]
Hi,

In producer example how can i implement the sasl parameters? like sasl_mecahnism. sasl_plain_user/pass etc?
i tried - 
**export KAFKA_CLIENT_ADDITIONAL_SETTINGS="security.protocol=SASL_PLAINTEXT;sasl.kerberos.service.name=username;sasl.kerberos.service.password=password;sasl.mechanism=PLAIN"**
But no result.

Thanks

**Comment by kenneth-jia** [comment]
The ref link from `librdkafka` might help, https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka
