### ISSUE TITLE
DEBUG confliction

### ISSUE THREAD

**Issue by zjufish** [morganstanley/modern-cpp-kafka#127]
it looks like below code conflicts with system DEBUG macro and produces a compile error with gcc10.1.0. should we use a different name or remove it given it is not used at all in code anyway?

<command-line>: error: expected unqualified-id before numeric constant
kafka/KafkaClient.h:198:34: note: in expansion of macro ‘DEBUG’
  198 |     static const constexpr char* DEBUG             = "debug";

**Comment by kenneth-jia** [comment]
Thanks, @zjufish!
As you said, the `DEBUG` is not used anymore, we should just remove it from `kafka/KafkaClient.h`.

**Comment by zjufish** [comment]
please make a fix and retag. thanks.
