### ISSUE TITLE
#define NOMINMAX is needed

### ISSUE THREAD

**Issue by Czybor** [morganstanley/modern-cpp-kafka#141]
#define NOMINMAX
#include <kafka/KafkaProducer.h>

int main()
{
	return 0;
}

**Comment by Czybor** [comment]
A library should always be used as it is. Here is an aditional step nessesary. So it differs for linux and windows users.

This is a bug!

**Comment by kenneth-jia** [comment]
Hi, @Czybor 
So far, I still have no idea about the problem you met. I would be much appreciated if there's more info attached (such as error messages, build env, etc)

**Comment by Czybor** [comment]
More info: A Windows user must add a compiler switch to avoid compile errors. This switch should be inside the library headers and depends from the OS.
