### ISSUE TITLE
C++-17/boost

### ISSUE THREAD

**Issue by Czybor** [morganstanley/modern-cpp-kafka#142]
The tests needs "boost" too. There is also an issue with the "boost" environment variable, "boost" must be installed, even with C++-17.

**Comment by kenneth-jia** [comment]
The `boost` is used by `tests` (and `tools`, etc), while it's not a pre-requirement to use the `modern-cpp-kafka` headers.
If you just include the `modern-cpp-kafka` API in a parent projects, no need to install `boost` (if with c++17).

**Comment by Czybor** [comment]
Change the project description, which does not reflect this. Users who don't whish to install "boost" can not use this library with all of its features! The C++-17 option is also buggy, because you must have installed "boost" on your system!

It's a question of clear usability.

**Comment by kenneth-jia** [comment]
> Users who don't whish to install "boost" can not use this library with all of its features! 

An easy to verify the `boost` dependency is,
1. Install the `librdkafka` library (manually, I'd suggest), but don't install `boost`.
2. Copy the `modern-cpp-kafka` headers (i.e. `include` directory) into your own project folder.
3. Try to use the `modern-cpp-kafka` API in your project. (make sure to build with C++17)

Then, if there's any failure, please attach the error messages.

**Comment by Czybor** [comment]
This is no solution. If i like to test the library or if i like to read the manuals i must build it with CMake, but this does not work because of bugs inside the build scripts.
