### ISSUE TITLE
"/usr/bin/ld: cannot find -lmodern-cpp-kafka-api" error message while building examples

### ISSUE THREAD

**Issue by barzan-hayati** [morganstanley/modern-cpp-kafka#151]
Hi. Thanks for your awesome repository.

I tried to build your examples by include related libraries to `CMakeList.txt`

```
include_directories(../include)
link_directories(../include)
```

after run `cmake CMakeList.txt` and `make` command it gives me this error:
```

[ 10%] Building CXX object CMakeFiles/kafka_async_producer_copy_payload.dir/kafka_async_producer_copy_payload.o
[ 20%] Linking CXX executable kafka_async_producer_copy_payload
/usr/bin/ld: cannot find -lmodern-cpp-kafka-api
collect2: error: ld returned 1 exit status
CMakeFiles/kafka_async_producer_copy_payload.dir/build.make:94: recipe for target 'kafka_async_producer_copy_payload' failed
make[2]: *** [kafka_async_producer_copy_payload] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/kafka_async_producer_copy_payload.dir/all' failed
make[1]: *** [CMakeFiles/kafka_async_producer_copy_payload.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

especially  this line:
`
/usr/bin/ld: cannot find -lmodern-cpp-kafka-api
`

How could I address **modern cpp kafka api** library? 
Thanks in advance

**Comment by kenneth-jia** [comment]
Hi, @barzan-hayati 
How does your project look like? (i.e. the configuration in `CMakeList.txt`, for the dependency towards `modern-cpp-kafka`) 
The `modern-cpp-kafka-api` is not a library to **link** with (`-lmodern-cpp-kafka-api`), instead, it's a header-only library (defined with `INTERFACE`, https://github.com/morganstanley/modern-cpp-kafka/blob/main/include/CMakeLists.txt)
Here's an example shows how an app depends on it (use `target_link_libraries`), https://github.com/morganstanley/modern-cpp-kafka/blob/main/examples/CMakeLists.txt#L6
