### ISSUE TITLE
std::min - issue when using Windows.h

### ISSUE THREAD

**Issue by Crashtein** [morganstanley/modern-cpp-kafka#165]
I am developing crossplatform microservice for Windows/Linux. In my code I use sleep timer from Windows.h (for delay when db connection fails). Windows.h is colliding with std::min, which is used in include/kafka/Log.h.
Problem is probably caused by '#define min' in Windows.h.
To have Modern C++ Kafka working properly in this case, there is a need to add #undef clause In include/kafka/Log.h:

> #pragma once
> 
> #include \<kafka/Project.h\>
> 
> #include \<kafka/Utility.h\>
> 
> #include \<algorithm\>
> #include \<array\>
> #include \<cassert\>
> #include \<functional\>
> #include \<iostream\>
> 
> **#undef min**

I have suggested a pull request for this issue. Please review it.

**Comment by kenneth-jia** [comment]
Hi, @Crashtein As you said, `windows.h` is conflicting the `std::min`, -- it's not fair to add the confusing `#undef min` in `include/kafka/Log.h`.
 
While you could workaround,
1. you could add a line of `#undef min` right after you including `include/kafka/Log.h`.
2. `#define NOMINMAX` before including `windows.h`, https://ms.stackenterprise.co/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included?site=StackOverflow
3. Include `include/kafka/Log.h` before including the `windows.h`, (`Log.h` would include `Project.h`, which calls `#define NOMINMAX` as well)

**Comment by stertingen** [comment]
Many C++ projects circumvent this problem by using `(std::min)(x, y)`.
`windows.h` defines `min` as functional macro which does not get expanded when wrapping `std::min` in parens.

There are other environments I am aware of where `min()` and `max()` are defined as macros. (`arduino.h`)

Real-world example: https://github.com/chriskohlhoff/asio/blob/ef4c4f337bb86d1edaefd74be825ec2e35c29324/asio/include/asio/buffer.hpp#L1793
