### ISSUE TITLE
Example of Record Value Being Non-String

### ISSUE THREAD

**Issue by adammpolak** [morganstanley/modern-cpp-kafka#174]
Is there a good example of how to send arbitrary binary data as a record value?

For instance, if the message is a vector of objects.

**Comment by kenneth-jia** [comment]
The "record value" (i.e. `kafka::Value`) is a `const buffer`, so it's fine to send a block of binary data. E.g. 
 https://github.com/morganstanley/modern-cpp-kafka/blob/main/examples/kafka_async_producer_not_copy_payload.cc#L39
While I don't quite understand what `a vector of objects` means? If you're trying to send a `std::vector<T>` directly, it would never work; if the `T` only for basic value types (no pointer, etc..), you could send its `data()` as payload.

**Comment by adammpolak** [comment]
@kenneth-jia 

How can I set a non-NullKey or set a header?

**Comment by kenneth-jia** [comment]
[Here's a testcase for non-NullKey and headers](https://github.com/morganstanley/modern-cpp-kafka/blob/v2022.10.12/tests/integration/TestKafkaConsumer.cc#L90)
[The utility function for the test](https://github.com/morganstanley/modern-cpp-kafka/blob/v2022.10.12/tests/utils/TestUtility.h#L180)
