### ISSUE TITLE
how can subcribe multi topic using only one kafka::clients::KafkaConsumer and thread

### ISSUE THREAD

**Issue by RyuShai** [morganstanley/modern-cpp-kafka#178]
Can i subcribe multi topic using one kafka::clients::KafkaConsumer in single thread ?

**Comment by kenneth-jia** [comment]
You could subscribe multiple topics with a single `KafkaConsumer`, while on the other side, each `KafkaConsumer` (or `KafkaProducer` would have multiple internal threads...
The `subscribe` interface: https://github.com/morganstanley/modern-cpp-kafka/blob/main/include/kafka/KafkaConsumer.h#L70
There're also some testcases about the multiple-topics subscription, e.g. https://github.com/morganstanley/modern-cpp-kafka/blob/main/tests/integration/TestKafkaConsumer.cc#L1706
