### ISSUE TITLE
Num partitions in the topic

### ISSUE THREAD

**Issue by alexeyeroshov** [morganstanley/modern-cpp-kafka#185]
Hi,

Is it possible to get the number of partitions in the topic?
In Admin* headers I see that it is possible to retrieve topic names only

**Comment by kenneth-jia** [comment]
Hi, @alexeyeroshov, 
It's quite simple, -- just with two steps,
1. `fetchBrokerMetadata` for a Kafka client, https://github.com/morganstanley/modern-cpp-kafka/blob/main/include/kafka/KafkaClient.h#L126
2. Get the size of `partitions()` (the map for partition->patitionInfo) from the `BrokerMetadata`, https://github.com/morganstanley/modern-cpp-kafka/blob/main/include/kafka/BrokerMetadata.h#L108

**Comment by alexeyeroshov** [comment]
Ah, yes, super easy :) Thank you!
