### ISSUE TITLE
question: how can I ensure that the memorey that record.headers() points to say valid?

### ISSUE THREAD

**Issue by jonathan-dev** [morganstanley/modern-cpp-kafka#191]
I am receiving kafka messages like it is done in  [this](https://github.com/morganstanley/modern-cpp-kafka/tree/main/examples/kafka_auto_commit_consumer.cc) example and from there I am passing the record.headers() through my application. But it seems that is the memory that it points to is invalidated after some point... how can I ensure that the memory stays alive? or what is the suggested way of dealing with this.

thanks

**Comment by kenneth-jia** [comment]
Hi, @jonathan-dev 
The `value` type of `header` is `const_buffer`, and the lifetime depends on the `ConsumerRecord`.
So, either you keep the `record` until it has been processed, or deep-copy the memory block for `header.value()` before releasing the `record`.

**Comment by jonathan-dev** [comment]
Ok. make sense. Thanks for the answer. I'll close this.
