### ISSUE TITLE
Minimum CMake version is too low.

### ISSUE THREAD

**Issue by vadtec** [morganstanley/modern-cpp-kafka#198]
CMakeLists.txt (main dir, tests/unit/) use cmake_path which is available from CMake 3.20 onward.

cmake_minimum_required(VERSION "3.8")

That should really be updated so that CMake will error out rather than blowing up with errors.

**Comment by kenneth-jia** [comment]
Good catch! 
Thank you, @vadtec!
Just fixed it with https://github.com/morganstanley/modern-cpp-kafka/pull/199
