### ISSUE TITLE
How to configure Kafka client to authenticate using `SASL_PLAINTEXT` and `SCRAM-SHA-256`?

### ISSUE THREAD

**Issue by baqeri** [morganstanley/modern-cpp-kafka#213]
How to configure the Kafka client to authenticate using `SASL_PLAINTEXT` and `SCRAM-SHA-256`?

When I configure Kafka consumer by this, it says:
```
N5kafka14KafkaExceptionE: 2023-07-05 19:51:10.546194: Local: Invalid argument or configuration [-186] (.../include/kafka/KafkaClient.h:429)
```

Does it throw such an exception because `modern-cpp-kafka` doesn't support it?

**Comment by kenneth-jia** [comment]
Hi, @baqeri
I don't think the problem still exists, -- it was fixed almost 2 years ago, https://github.com/morganstanley/modern-cpp-kafka/pull/86

**Comment by eaxeax** [comment]
i have the same trouble :(

**Comment by Neustradamus** [comment]
To follow this ticket

**Comment by Neustradamus** [comment]
@baqeri: Where is the fix? Without a solution, do not close a ticket!

**Comment by eaxeax** [comment]
> @baqeri: Where is the fix? Without a solution, do not close a ticket!



> the problem is on librdkafka side. You need to compile lib with sasl support
