### ISSUE TITLE
C++14 compilation is broken with latest release

### ISSUE THREAD

**Issue by gobprasad** [morganstanley/modern-cpp-kafka#30]
Unable to compile with C++14 compiler and boost, getting below error -

include/kafka/Error.h:90:13: error: no template named 'optional' in namespace 'std'; did you mean 'Optional'?
    virtual std::optional<bool> isFatal()     const { return rd_kafka_error_is_fatal(_rkError.get()); }
            ^~~~~~~~~~~~~
            Optional

/include/kafka/Error.h:112:5: error: no template named 'optional' in namespace 'std'; did you mean 'Optional'?
    std::optional<bool> isFatal()     const override { return {}; }
    ^~~~~~~~~~~~~
    Optional

/include/kafka/Types.h:25:1: note: 'Optional' declared here
using Optional = boost::optional<T>;
^

/include/kafka/Error.h:113:5: error: no template named 'optional' in namespace 'std'; did you mean 'Optional'?
    std::optional<bool> isRetriable() const override { return {}; }
    ^~~~~~~~~~~~~
    Optional

**Comment by kenneth-jia** [comment]
Thank you for pointing it out, @gobprasad 👍
Because of the `set(CMAKE_CXX_STANDARD 17)` in `CMakeLists.txt`, the `-std=cxx14` flag has been ignored in the CI build!
Let me fix it later.
