### ISSUE TITLE
unit test compilation issue with gtest

### ISSUE THREAD

**Issue by gobprasad** [morganstanley/modern-cpp-kafka#31]
Unable to build unit tests, getting below errors.

/tests/unit/TestProperties.cc:20:5: error: no matching conversion for functional-style cast from 'boost::optional<std::__1::basic_string<char> >' to '::testing::AssertionResult'
    EXPECT_TRUE(getBootstrapServers);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
googletest/dist/include/gtest/gtest.h:1920:3: note: expanded from macro 'EXPECT_TRUE'
  GTEST_TEST_BOOLEAN_(condition, #condition, false, true, \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
googletest/dist/include/gtest/internal/gtest-internal.h:1111:7: note: expanded from macro 'GTEST_TEST_BOOLEAN_'
      ::testing::AssertionResult(expression)) \
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
googletest/dist/include/gtest/gtest.h:261:3: note: candidate constructor not viable: no known conversion from 'boost::optional<std::__1::basic_string<char> >' to 'const testing::AssertionResult' for 1st argument
  AssertionResult(const AssertionResult& other);
  ^
googletest/dist/include/gtest/gtest.h:263:12: note: candidate constructor not viable: no known conversion from 'boost::optional<std::__1::basic_string<char> >' to 'bool' for 1st argument
  explicit AssertionResult(bool success) : success_(success) {}
           ^
1 error generated.
*** Error code 1

**Comment by kenneth-jia** [comment]
What version of googletest are you using?
How about trying with googletest  `v1.10.0`? (the version used by CI), https://github.com/morganstanley/modern-cpp-kafka/blob/main/.github/workflows/kafka_api_ci_tests.yml#L99

**Comment by gobprasad** [comment]
Issue was with gtest library, with updated gtest, this issue is no longer seen.
