### ISSUE TITLE
Timestamp related test cases should include Time Zone in calculation

### ISSUE THREAD

**Issue by gobprasad** [morganstanley/modern-cpp-kafka#32]
I see timestamp file is not using Time-Zone related information which lead to unit test failures when running in different time zone.
I am running these test cases in India (+5:30), I have to manually adjust this timezone value in actual calculations

**Comment by kenneth-jia** [comment]
OH, I was using a loose RE (e.g,  `(2020-01-.. ..:01:01\.123)`) to match the timestamp to avoid test failures from TimeZone differences. Seems doesn't work? The tests `Timestamp.*` would print out the timestamps as well? Could you please help attach the `cout` please? Thanks!
