### ISSUE TITLE
examples with tls/mtls

### ISSUE THREAD

**Issue by nareshv** [morganstanley/modern-cpp-kafka#40]
Does this work with tls/mtls schemes ? any docs would be appreciated.

**Comment by kenneth-jia** [comment]
The `modern-cpp-kafka` is only a C++ wrapper over `librdkafka`, thus the tls-related functionality resides in `librdkafka`.
Luckily, `librdkafka` documents well for the case,
1. To enable TLS support, the first thing is, make sure build `librdkafka` with ssl support, https://github.com/edenhill/librdkafka/wiki/Dependencies
2. Configure the kafka client properly, https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka.
You code might be something likes,
```
kafka::Properties props ({ {"bootstrap.servers",  xxxxxx},
                                         {"security.protocol", "ssl"},
                                         {"ssl.ca.location", "ca-cert"},
                                         {"ssl.certificate.location", "client_?????_client.pem"},
                                         {"ssl.key.location", "client_?????_client.key"},
                                         {"ssl.key.password", xxxx}
                                       });
KafkaAutoCommitConsumer consumer(props);
```

**Comment by nareshv** [comment]
great. thanks.
