### ISSUE TITLE
documentation out of date with examples, latest code

### ISSUE THREAD

**Issue by nareshv** [morganstanley/modern-cpp-kafka#41]
Hello, are the examples/ and wiki out of date with the latest code, i am getting errors running examples and code samples from wiki pages.

**Comment by kenneth-jia** [comment]
Could you be more specific please?
The examples would be compiled with each CI, https://github.com/morganstanley/modern-cpp-kafka/tree/main/examples, -- so I guess you didn't mean that. And, what is the (out-of-dated) wiki page link?

**Comment by nareshv** [comment]
I have spent some more time going through the github examples and the files deployed as part of this. Somehow the librdkafka also ships c++ headers, i think there is some mismatch with them.
