### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by MPeli** [morganstanley/modern-cpp-kafka#48]
Hi,

thank you for your work. I was wondering whether the C++wrapper has been tested on Windows. I tried to build a project using just the headers and ran into several compilation issues (missing syslog.h...).

Thank you, Martin.

Visual Studio 2019, toolset v142, C++17

**Comment by kenneth-jia** [comment]
You're right, the C++ wrapper doesn't support windows yet, while it should.
Let me have a try these days. 🙂

**Comment by kenneth-jia** [comment]
@MPeli I just merged a PR which fixed the compilation errors (while still needs more effort to complete the windows CI jobs) Please have a try. Cheers! 😀
