### ISSUE TITLE
`partitionsFor` API to get the number of partitions for a topic

### ISSUE THREAD

**Issue by niyue** [morganstanley/modern-cpp-kafka#52]
Thanks for creating the project, and this makes Kafka easier to consume in C++.

I wonder if there is an API to get the number of partitions for a given topic, like Java's [`partitionsFor`](https://kafka.apache.org/24/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#partitionsFor-java.lang.String-) or kafka-python's [`partitions_for_topic`](https://kafka-python.readthedocs.io/en/master/_modules/kafka/consumer/group.html#KafkaConsumer.partitions_for_topic).

If there is no such API, is it expected for others to contribute such an API to this project?

**Comment by kenneth-jia** [comment]
A few steps to get the job done,
1. Call `fetchBrokerMetadata(...)` (with a `KafkaProducer`, `KafkaConsumer`, or `AdminClient`)
https://github.com/morganstanley/modern-cpp-kafka/blob/main/include/kafka/KafkaClient.h#L107
2. Get the `partitions()` from the `BrokerMetadata`
https://github.com/morganstanley/modern-cpp-kafka/blob/main/include/kafka/BrokerMetadata.h#L108
3. It's a map, including the `PartitionInfo` for each `Partition`
https://github.com/morganstanley/modern-cpp-kafka/blob/main/include/kafka/BrokerMetadata.h#L56
