### ISSUE TITLE
cooperative rebalance support

### ISSUE THREAD

**Issue by NinaPeng** [morganstanley/modern-cpp-kafka#56]
Hi there,

Thank you for your great work. 

When I'm using consumer with property: `{"partition.assignment.strategy", "cooperative-sticky"}`, I found it failed with message: 
```shell
WARNING KafkaConsumer[c3f918a8-7561f2c7] ASSIGN | [thrd:main]: Group "test": application *assign() call failed: Changes to the current assignment must be made using incremental_assign() or incremental_unassign() when rebalance protocol type is COOPERATIVE
```
However, cooperative seems to be default assigner in future: https://issues.apache.org/jira/browse/KAFKA-12473 . I think it's necessary to make client support cooperative assignment strategy.

I found an example in librdkafka for cooperative rebalance callback:
```cpp
switch (err) {
       case RD_KAFKA_RESP_ERR__ASSIGN_PARTITIONS:
             // application may load offets from arbitrary external
             // storage here and update \p partitions
             if (!strcmp(rd_kafka_rebalance_protocol(rk), "COOPERATIVE"))
                     rd_kafka_incremental_assign(rk, partitions);
             else // EAGER
                     rd_kafka_assign(rk, partitions);
             break;

        case RD_KAFKA_RESP_ERR__REVOKE_PARTITIONS:
             if (manual_commits) // Optional explicit manual commit
                 rd_kafka_commit(rk, partitions, 0); // sync commit

             if (!strcmp(rd_kafka_rebalance_protocol(rk), "COOPERATIVE"))
                     rd_kafka_incremental_unassign(rk, partitions);
             else // EAGER
                     rd_kafka_assign(rk, NULL);
             break;

        default:
             handle_unlikely_error(err);
             rd_kafka_assign(rk, NULL); // sync state
             break;
         }
    }
```

Seems `KafkaConsumer::_assign` can be changed to align with incremental assignment

**Comment by NinaPeng** [comment]
Based on the example, I try to make changes for `KafkaConsumer::rebalanceCallback` in https://github.com/morganstanley/modern-cpp-kafka/pull/55. It seems work for cooperative-sticky strategy.
Please let me know if this helps or if there is anything I need to change. Thanks.

**Comment by kenneth-jia** [comment]
Thanks! The commit has been merged into a feature branch `Feature-SupportCooperativeRebalance`, which would be merged into `main` branch after some refinements (would be done at some later time). 😄

**Comment by kenneth-jia** [comment]
@NinaPeng The feature branch has been merged into `master`  with https://github.com/morganstanley/modern-cpp-kafka/pull/58
Please pull the latest code change and retry. Cheers!
