### ISSUE TITLE
fetchBrokerMetadata API with `all_topics` parameter exposed

### ISSUE THREAD

**Issue by niyue** [morganstanley/modern-cpp-kafka#66]
Currently, the `fetchBrokerMetadata` API in `KafkaClient` can be used to retrieve broker metadata. In my case, I know up front some topic is changed and would like to retrieve the latest topic information and trigger a rebalance by calling this API. Internally, it calls librdkafka's `rd_kafka_metadata` API, but so far the `all_topics` parameter of `rd_kafka_metadata` API is not exposed yet and is hard coded to be `false` in `fetchBrokerMetadata`.

```
rd_kafka_resp_err_t err = rd_kafka_metadata(getClientHandle(), false, rkt.get(), &rk_metadata, convertMsDurationToInt(timeout));
                                                                 |__ `all_topics` is hard coded here
```

Here's librdkafka's description about this parameter:
```
all_topics  if non-zero: request info about all topics in cluster,
                  if zero: only request info about locally known topics.

@remark Consumer: If \p all_topics is non-zero the Metadata response
information may trigger a re-join if any subscribed topics
have changed partition count or existence state.
```

I wonder if there is any chance we could expose this parameter as an optional parameter for the `fetchBrokerMetadata` API so that client can control some behavior here using this parameter.

**Comment by kenneth-jia** [comment]
Yes, the `all_topics` is set as `false`, to avoid the result being too HUGE! (who knows how many topics could be deployed in the cluster?😅)
An alternative approach would be: `AdminClient::listTopics()` + `KafkaClient::fetchBrokerMetadata(...)`, -- just not sure whether that is convenient for your case?

**Comment by niyue** [comment]
Sorry for the late reply, I think for this API, the key difference is if `all_topics` is set to false (zero value), librdkafka won't trigger re-join according to the doc above:
```
If all_topics is non-zero the Metadata response
information may trigger a re-join if any subscribed topics
have changed partition count or existence state
```
Even if client can use `AdminClient::listTopics()` + `KafkaClient::fetchBrokerMetadata(...)` combination to retrieve metadata, this won't trigger re-join due to subscription change.

**Comment by kenneth-jia** [comment]
Before trying with `all_topics=true`, we should consider how we test it, -- or being more specific, how to write our testcases.
I don't quite understand `I know up front some topic is changed and would like to retrieve the latest topic information and trigger a rebalance by calling this API` -- did you mean the following?
1. Start a consumer, subscribe to some topic, and get the brokerMetadata
2. Use an AdminClient to delete the Kafka topic, and re-create the topic, but with different properties (e.g, partition number, replication factor, etc)
3. Use the consumer to fetch the brokerMetadata again, the new brokerMetadata should be different from the old one

**Comment by niyue** [comment]
Hi @kenneth-jia, thanks for the response. 

In my case, the situation is like this:
1) consumer subscribes to some topic pattern 
2) end users create some topic via UI, we would like to notify consumers immediately a topic is created and rebalance for newly created topic. And it seems the only API for doing this is using the `all_topics` parameter in librdkafka to trigger rebalance. 

It doesn't have to be a re-created topic like you said, in my case, the situation looks like:
1) Start a consumer, subscribe to some topic **pattern**, and get the brokerMetadata
2) Use an AdminClient to create a new topic (which matches the pattern above)
3) Use the consumer to fetch the brokerMetadata again, the new brokerMetadata should include the new topic, at the same time, since the subscription changes, the consumer will re-join the group

The issue I would like to address is by default kafka refreshes its metadata and triggers rebalance every 300 seconds (5 minutes), before the rebalance happens, the data for the new topic won't be fetched by consumer, and this latency is too high in my case, and I would like to reduce it as much as possible.

**Comment by kenneth-jia** [comment]
Thanks for the details description, @niyue 
I'll work our a PR (together with some testcase) these days. Cheers! 😊
