### ISSUE TITLE
Support librdkafka 1.8.2

### ISSUE THREAD

**Issue by alexolog** [morganstanley/modern-cpp-kafka#94]
Please add support for librdkafka [1.8.0](https://github.com/edenhill/librdkafka/releases/tag/v1.8.0).

**Comment by kenneth-jia** [comment]
The trouble is, the librdkafka `v1.8.0`&`v1.8.2` would fail two robustness testcases: Robustness testcase `KafkaConsumer::AlwaysFinishClosing_ManuallyPollEvents`, `KafkaConsumer::CommitOffsetWhileBrokersStop`.
Briefly speaking, the consumer would stuck at `rd_kafka_consumer_close` if there're on-going offset-commit request but the brokers are down by accident.

**Comment by KevDi** [comment]
Is there still the plan to update the library to support `v1.8.x` of the librdkafka?

**Comment by aambroze** [comment]
+1 on updating the library with support of more recent versions of librdkafka. 1.8.2 is packaged by default in [Yocto](https://layers.openembedded.org/layerindex/recipe/168226/).

Needing to downgrade the library just to use your wrapper is an obstacle in serious projects, where stable and up-to-date (security and feature-wise) versions are preferred.

**Comment by kenneth-jia** [comment]
@KevDi @aambroze One thing I want to clarify a bit is, the c++ wrapper would not block people from using a newer librdkafka release. The newer librdkafka releases (`v1.8.x`) would fail some testcases, in a very corner case, -- most of the times, people wouldn't care/notice about this behavior change (from librdkafka) and they are free to go with `modern-cpp-kafka` and `librdkafka v1.8.x`.
Honestly speaking, I'm expecting a newer librdkafka release which might accidentally fix the problem. If with no luck, I have to find some timeslot to do some further investigation (for this librdkafka issue)

**Comment by aambroze** [comment]
@kenneth-jia Thanks for your reply. Do you mean that issues mentioned here https://github.com/morganstanley/modern-cpp-kafka/issues/94#issuecomment-947252075 are the only known problems with the library?
